### ISSUE TITLE
Players can use the side barriers to build faster

### ISSUE THREAD

**Issue by mounderfod** [NucleoidMC/mineout#7]
![image](https://user-images.githubusercontent.com/24373708/101632789-466e5d80-3a1e-11eb-88db-76c6f9e23587.png)
This can be rectified by reducing the `buildable` region size so that people cannot build on the side blocks.

**Comment by Gegy** [comment]
Closed in https://github.com/NucleoidMC/mineout/commit/1fed0bc88db49a959dd3b9880d80f64d15db08ff

**Comment by mounderfod** [comment]
thanks :)
